defaults:
  - planner@sub_agents.Planner
  - synthesizer@sub_agents.Synthesizer
  - search@sub_agents.Search
  - critic@sub_agents.Critic
  - _self_

name: "Main"
description: "This agent orchestrates the workflow of the system, coordinating between the planner, synthesizer, search, and critic agents to answer user queries."
configs:
  model: "gemini-2.5-pro"
  prompt: prompts/main.txt
  prompt_args:
    max_revision: 3
