name: "Main"
sub_agents:
  - Planner
configs:
  model: "gemini-2.5-flash"
  prompt: "You are a helpful assistant. Your task is to answer questions based on the provided context. If the answer is not in the context, respond with 'I don't know'."
