defaults:
  - planner@sub_agents.Planner
  - synthesizer@sub_agents.Synthesizer
  - search@sub_agents.Search
  - critic@sub_agents.Critic
  - _self_

name: "Main"
configs:
  model: "gemini-2.5-pro"
  prompt: prompts/main.txt
  prompt_args:
    max_revision: 3
