name: "Planner"
description: "Planner agent for task planning and execution"
configs:
  model: "gemini-2.5-flash"
  prompt: "prompts/planner.txt"
  prompt_args:
    max_steps: 10
  function_tools:
    - mem0_search
    - mem0_add
