name: "Search"
description: "This agent performs searches to find relevant information for the user's query and given search plan."
configs:
  model: "gemini-2.5-flash-lite-preview-06-17"
  prompt: "prompts/search.txt"
  function_tools:
    - kb_weaviate
    - perplexity_search
    - tavily_search
