name: "Synthesizer"
description: "This agent synthesizes information from various sources to create a coherent response to the user's query."
configs:
  model: "gemini-2.5-flash"
  prompt: "prompts/synthesizer.txt"
