extra_css:
  - stylesheets/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JeiKeiLim/deep-research-agent-framework-toolkit
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Agent Builder: agent-builder.md
  - Creating Your Own Agent: creating-agents.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            separate_signature: true
            show_overloads: true
            show_submodules: true
            show_root_heading: false
            show_root_full_path: true
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
repo_url: https://github.com/JeiKeiLim/deep-research-agent-framework-toolkit
repo_name: JeiKeiLim/deep-research-agent-framework-toolkit
site_name: Deep Research Agent Framework Toolkit
theme:
  custom_dir: docs/overrides
  favicon: assets/draft_favicon.ico
  logo: assets/draft_icon.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
