name: "ArvixCritic"
description: "This agent evaluates the synthesized analysis of an arXiv paper or topic, providing feedback on its accuracy, relevance, and completeness."
configs:
  model: "gemini-2.5-flash"
  prompt: "prompts/arxiv_agent/critic.txt"
