defaults:
  - agents/main@agents.Main
  - agents/planner@agents.Planner
  - agents/synthesizer@agents.Synthesizer
  - agents/search@agents.Search
  - agents/critic@agents.Critic
  - agents/evaluator@evaluator
  - _self_

agent_configs:
  max_revision: 3
  orchestration_mode: 'agent' # "agent" or "sequential"
  enable_history: true
  history_storage_dir: 'conversation_history'
  max_messages: 5 # 대화 히스토리에서 가져올 최대 메시지 수

evaluation_configs:
  langfuse_dataset_name: 'test_questions'
  run_name: '2025_0806_test_run_03'
  run_async: False
  limit: -1
