defaults:
  - agents/main@agents.Main
  - agents/planner@agents.Planner
  - agents/synthesizer@agents.Synthesizer
  - agents/weaviate_tool@agents.WeaviateTool 
  - agents/perplexity_tool@agents.PerplexityTool
  # - agents/search@agents.Search
  - agents/critic@agents.Critic
  - _self_

agent_configs:
  max_revision: 3
