name: "Planner"
description: "Use this agent **first** to perform **Step 1: PLAN**. It takes the user's raw query and creates a structured search plan. Do not use for any other purpose."
configs:
  model: "gemini-2.5-flash"
  prompt: "prompts/draft_agent/planner.txt"
  prompt_args:
    max_steps: 10
